### ISSUE TITLE
'Hierarchy - Top' layout is not applying hierarchical physics

### ISSUE THREAD

**Issue by patrickmcelwee** [grtjn/ml-visjs-graph.js#16]
This is known good in https://github.com/grtjn/ml-visjs-graph.js/tree/0.4.0 and known bad in whatever version @grtjn  is running locally :-). 

Creating this issue to help with debugging.

**Comment by grtjn** [comment]
You are right. I observed this when I was working on #15, and edge styling was getting lost altogether. I was trying to pass through complete options in setOptions to resolve this, but that just made things worse. In the end I am still keeping a shadow options object, but passing in diffs only to setOptions (except initially). The culprit with the edges was, that I had to pass through a complete edges.smooth object, not just a loose edges.smooth.type property.

**Comment by grtjn** [comment]
It was actually related to #11, or maybe both 11 and 15..
