### ISSUE TITLE
gracefully fallback when fontawesome not available

### ISSUE THREAD

**Issue by patrickmcelwee** [grtjn/ml-visjs-graph.js#17]
I think this is just a nice-to-have now, not necessary. But, in the React app without fontawesome available, it looks like this: 
<img width="366" alt="screen shot 2018-08-24 at 12 11 01 pm" src="https://user-images.githubusercontent.com/808015/44595433-e5f87b00-a796-11e8-904a-c89b10c45937.png">

**Comment by grtjn** [comment]
I was thinking to drop the fontawesome class on the wrapping template, and add a styling option that can take a fontawesome value.. that should give you default icons..

**Comment by grtjn** [comment]
It now no longer uses fontawesome by default. Make sure to link both vis.css and ml-visjs-graph.js.less in your wrapper component though.

**Comment by patrickmcelwee** [comment]
@grtjn , Dave Grant is finding what I find in the React version, which is that the linkCount text is not centered. It looks like this:

![screen shot 2018-10-25 at 3 13 52 pm](https://user-images.githubusercontent.com/808015/47525013-31e4a080-d86a-11e8-94ea-5aa9471853b0.png)

Do you think this is because of a styling difference (because I am not using fontawesome)?

**Comment by grtjn** [comment]
I may have failed to thoroughly test this. Maybe this is a good reason for a short screen share tomorrow?

**Comment by grtjn** [comment]
The mis-alignment of orb-labels is not related to fontawesome. I opened #34 for that, and closing this ticket..

**Comment by grtjn** [comment]
Moved it back to original milestone..
