### ISSUE TITLE
Fix endless image errors

### ISSUE THREAD

**Issue by patrickmcelwee** [grtjn/ml-visjs-graph.js#21]
With the current setup, dist/images/generic.png is not available in my
React app. I tried prepending the node_modules path, which also
failed.

It fails rather spectacularly, quickly generating tens of thousands of
failed network requests and console errors, eventually crashing the tab.
I think it is the issue referenced here:
almende/vis#3338

I found that removing the brokenImage property worked. The nodes just
look like circles.

It would be better to figure out a framework-agnostic way to include images, but I'm not sure how to do that, and in the meantime, better to patch this issue. How did you do it in Vue? Did you set up custom image paths in the consuming app?

**Comment by grtjn** [comment]
I think we should just drop the default circularImage shape altogether.. could you update the PR?

**Comment by patrickmcelwee** [comment]
I updated the PR. Ready to merge? (I need it to finish the React graph component.)

**Comment by grtjn** [comment]
Merged
