### ISSUE TITLE
Note that users need gulp-cli globally now

### ISSUE THREAD

**Issue by patrickmcelwee** [grtjn/ml-visjs-graph.js#22]
Instead of gulp. See the link included in the README for more
information. I got an error when I used my global gulp:

    gulpInst.start.apply(gulpInst, toRun);
                  ^

    TypeError: Cannot read property 'apply' of undefined

**Comment by grtjn** [comment]
did you update both globally and locally?

**Comment by patrickmcelwee** [comment]
I should have said "contributors" rather than "users" ... this is only for those who are building this library.

I have gulp@4.0.0 locally, which gave me that error, and gulp-cli@2.0.1

**Comment by grtjn** [comment]
I installed gulp@4 globally and locally, and that ran fine.. hmm..

**Comment by grtjn** [comment]
I never installed gulp-cli for sure.. :|

**Comment by grtjn** [comment]
on second thought, my laptop disagrees:

$ gulp -v
[20:33:23] CLI version 2.0.1
[20:33:23] Local version 4.0.0

**Comment by grtjn** [comment]
Right, there you go, this explains:

$ npm list -g gulp-cli
/usr/local/lib
└─┬ gulp@4.0.0
       └── gulp-cli@2.0.1 

gulp-cli is a dependency of gulp v4..

**Comment by grtjn** [comment]
Anyhow, gulp-cli is indeed the recommended install package, merged the PR..
