### ISSUE TITLE
How to make layout dropdown reflect different initial layout?

### ISSUE THREAD

**Issue by patrickmcelwee** [grtjn/ml-visjs-graph.js#28]
When I set the initial layout to 'hierarchyTop' by called `graph.network.setLayout('hierarchyTop')`, the layout changes, but the dropdown select selection still shows "standard".

**Comment by patrickmcelwee** [comment]
The same thing is true for me for the physics checkbox.

**Comment by grtjn** [comment]
See also code snippet in #27, invoke setLayout and setPhysics on `graph` instead. I added those for this purpose recently..

**Comment by patrickmcelwee** [comment]
Works great! Thanks.
