### ISSUE TITLE
Apply fit after NetworkManager.setData

### ISSUE THREAD

**Issue by grtjn** [grtjn/ml-visjs-graph.js#9]

**Comment by patrickmcelwee** [comment]
btw ... we were automatically fitting like this with ml-visjs-graph-ng, and turning that off was something I was asked for a lot. I'm really not sure which behavior should be the default

**Comment by grtjn** [comment]
I think that was stabilize, or stabilize+fit. Stabilize can cause the graph to get reshuffled. A fit is just a zoom out.

**Comment by grtjn** [comment]
Reopening this. You sometimes want to push graph updates by calling setData with changed data, and once drawn, you don't want to fit again. Someone might have zoomed in on purpose.

E.g. only apply fit initially (when there was no data before yet).

**Comment by grtjn** [comment]
False alarm. I was calling fit whenever node or edge changes were detected in the Vue-wrapper. The library only applies fit initially, which should be okay I think..
